### ISSUE TITLE
[TODO] 20230329 까지

### ISSUE THREAD

**Issue by yongjulejule** [jis-kim/my-little-nest#1]
- [x] #2
- [x] #4
  - [x] 닉네임 변경 가능
  - [x] 회원 삭제 가능
- [x] #3
- [ ] #5
  - 유저 A 와 유저 B 가 있다.
  - A 가 "팔로잉" 버튼을 눌러 B 를 팔로잉 하면, A 의 팔로잉 버튼은 팔로잉 취소 버튼으로 바뀐다.
  - B 는 A 가 팔로잉 했을 때, "A 가 당신을 팔로잉 했습니다~!" 라는 alert 메시지를 받는다.
  - 다른 유저들은 아무 메시지도 받지 않는다.
  - 새로고침 시에도 팔로잉 상태가 유지되어야 한다.

**Comment by yongjulejule** [comment]
@jis-kim 
- [ ] 팔로잉 시스템 만들기
  - 유저 A 와 유저 B 가 있다.
  - A 가 "팔로잉" 버튼을 눌러 B 를 팔로잉 하면, A 의 팔로잉 버튼은 팔로잉 취소 버튼으로 바뀐다.
  - B 는 A 가 팔로잉 했을 때, "A 가 당신을 팔로잉 했습니다~!" 라는 alert 메시지를 받는다.
  - 다른 유저들은 아무 메시지도 받지 않는다.
  - 새로고침 시에도 팔로잉 상태가 유지되어야 한다.
